spring.application.name: OwlpotServer
# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sky-take-out
    username: root
    password: 622103
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB        # 单个文件最大上传大小,默认1MB
      max-request-size: 100MB     # 单个请求最大上传大小，默认10MB
  main:
    banner-mode: off              # 关闭spring图标

# MyBatis 配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 指定日志输出控制台
    map-underscore-to-camel-case: true                    # 开启驼峰命名映射

# MyBatis-plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 指定日志输出控制台
    map-underscore-to-camel-case: true                    # 开启驼峰命名映射
  global-config:
    banner: false                                       # 关闭图标
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
# 日志配置
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: DEBUG # 开启事务日志

# JWT配置
jwt:
  secret: "YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYQ=="
  expiration: 3600000  # 1小时（单位：毫秒）

# knife4j配置
knife4j:
  enable: false  # 生产环境关闭

# springdoc配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 路径
    enabled: true
  api-docs:
    path: /swapper/api-docs      # API 文档路径
    enabled: true